version: "3"

services:
  app-dev:
    container_name: api-dev
    build:
      context: .
      dockerfile: .docker/app.dev.dockerfile
    restart: on-failure
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/test

  mongo:
    container_name: mongo-dev
    image: mvertes/alpine-mongo
    restart: on-failure
    volumes:
      - ./data:/data/db
