# version: "3"

# services:
#   app:
#     container_name: api
#     build:
#       context: .
#       dockerfile: .docker/app.prod.dockerfile
#     restart: on-failure
#     ports:
#       - "3000:3000"
version: "3"

services:
  app-dev:
    container_name: api-dev
    build:
      context: .
      dockerfile: .docker/app.dev.dockerfile
    volumes:
      - .:/usr/src
      - ./package.json:/usr/src/package.json
      - ./package-lock.json:/usr/src/package-lock.json
      # this is a workaround to prevent host node_modules from accidently getting mounted in container
      # in case you want to use node/npm both outside container for test/lint etc. and also inside container
      # this will overwrite the default node_modules dir in container so it won't conflict with our
      # /opt/node_modules location. Thanks to PR from @brnluiz
      - notused:/usr/src/node_modules
      # - /usr/src/node_modules
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/test

  mongo:
    container_name: mongo-dev
    image: mvertes/alpine-mongo
    volumes:
      - ./data:/data/db
    # ports:
    #   - "27017:27017"

volumes:
  notused:
